version: "3.7"
services:
  postgres-service:
    container_name: postgres-service
    image: 'postgres:13.11'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '12345:5432'
    networks:
      - somenetwork
  contact-book:
    container_name: book-order
    build: .
    networks:
      - somenetwork
    ports:
      - "9898:9898"
    depends_on:
      - postgres-service
    environment:
      - SERVER_PORT=9898
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=secret
      - POSTGRES_URL=jdbc:postgresql://postgres-service/postgres?currentSchema=public
networks:
  somenetwork:
    driver: bridge